vich_uploader:
    db_driver: orm

    mappings:
        entreprises:
            uri_prefix: /images/entreprises
            upload_destination: '%kernel.project_dir%/public/images/entreprises'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        bureau:
            uri_prefix: /images/bureau
            upload_destination: '%kernel.project_dir%/public/images/bureau'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        challenges:
            uri_prefix: /images/challenges
            upload_destination: '%kernel.project_dir%/public/images/challenges'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        content:
            uri_prefix: /images/content
            upload_destination: '%kernel.project_dir%/public/images/content'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true